<a href="https://colab.research.google.com/github/Mohammad-sadik/Daily_codes/blob/main/Numpy/NumPy_Tutorial_In_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

## List vs NumPy - Performance Comparison (Time Taken)

In [1]:
from time import process_time

We first create a list and record its processing time. Then, we perform a mathematical operation on the list and record its timing again. This helps us determine how much time is required for that mathematical operation.

In [4]:
python_list =[i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
execution_time = end_time - start_time
print(execution_time)

0.0010955500000000562


In [6]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array +=5
end_time = process_time()
execution_time = end_time - start_time
print(execution_time)


0.0003823899999999547


**Observation:** NumPy arrays perform operations significantly faster than Python lists due to optimized memory and vectorized operations.

##Creating Numpy arrays and convert a list to a NumPy array

In [7]:
#List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
list2=[1,2,3,4,5]
np_array = np.asarray(list2)
print(np_array)
print(type(np_array))
print(np_array.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


##Creating 1D and 2D arrays



###1D Array (One-Dimensional Array)

A 1D array is like a list of elements.

It has only one axis (row or column).

In [11]:

a = np.array([1,2,3,4])
print(a)
a.shape #(4,) (only one dimension)

[1 2 3 4]


(4,)

###2D Array (Two-Dimensional Array)
A 2D array is like a table or a matrix (rows and columns).

It has two axes (rows and columns).

In [12]:
b = np.array(([1,2,3,4],[4,5,6,7],[8, 9, 10, 11]))
print(b)
b.shape #(2 rows,3 columns)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)

###Put values in floating points

In [ ]:
c = np.array(([1,2,3,4],[4,5,6,7]), dtype=float)
print(c)
c.shape #(2 rows,3 columns)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


(2, 4)

###3D Array (Two-Dimensional Array)

In [13]:
d = np.array([[[1,2,3,4],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])
print(d)
d.shape

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


(2, 2, 4)

##Initial Placeholders in NumPy

###1. Creating an Array of Zeros (np.zeros())

Creates an array filled with zeros.

In [ ]:
a = np.zeros((3,3))
print(a)
type(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


###2. Creating an Array of Ones (np.ones())
Creates an array filled with ones.

In [ ]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


###3. Creating an Array with a Constant Value (np.full())
Creates an array with a specific constant value.

In [ ]:
c = np.full((3,3),2, dtype=float)
print(c)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


###4. Creating an Identity Matrix (np.eye())
Creates a square identity matrix (diagonal elements = 1, others = 0).*italicized text*

In [ ]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###5. Creating a Linearly Spaced Array (np.linspace())
Creates an array with evenly spaced values.

np.linspace(start, stop, num) (Based on Count)

Generates a specific number of evenly spaced values between start and stop, inclusive.

You specify how many values (num) you want.

In [ ]:
e = np.linspace(10,30,5)
print(e)

[10. 15. 20. 25. 30.]


###6. Creating a Range of Values (np.arange())
Creates an array with values in a range.

np.arange(start, stop, step) (Based on Step Size)

Generates values from start to less than stop, with a fixed step size (step).

You specify the step size, not the number of elements.

In [ ]:
f = np.arange(10,30,5)
print(f)

[10 15 20 25]


##Create a NumPy array with random values


###Random integer values array within a specific range

In [ ]:
x = np.random.random((3,3)) #value btw 0 and less than 1, also data type is float
print(x)

[[0.33906657 0.81063685 0.35310269]
 [0.23590516 0.17926631 0.6810071 ]
 [0.26076398 0.98784132 0.36075083]]


###Random integer values array within a specific range

In [ ]:
y = np.random.randint(10,100,(3,5))
print(y)

[[26 21 67 44 27]
 [69 61 87 31 40]
 [48 95 20 86 17]]


##Analysing a NumPy array

###Create a NumPy array

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

###Basic Information

In [ ]:
print("Array:\n", arr)
print("Shape:", arr.shape)  # (rows, columns)
print("Size:", arr.size)  # Total elements
print("Data Type:", arr.dtype)  # Data type
print("Dimensions:", arr.ndim)  # Number of dimensions

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
Size: 9
Data Type: int64
Dimensions: 2


###Statistical Analysis

In [ ]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Min:", np.min(arr), "Max:", np.max(arr))
print("Sum:", np.sum(arr))

Mean: 50.0
Median: 50.0
Standard Deviation: 25.81988897471611
Variance: 666.6666666666666
Min: 10 Max: 90
Sum: 450



###Element-wise Operations

In [ ]:
print("Square of each element:\n", np.square(arr))
print("Log of each element:\n", np.log(arr))

Square of each element:
 [[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]
Log of each element:
 [[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]
 [4.24849524 4.38202663 4.49980967]]



###Indexing & Slicing

In [ ]:
print("First row:", arr[0])
print("First column:", arr[:, 0])
print("Element at (1,2):", arr[1, 2])
print("Last row:", arr[-1])

First row: [10 20 30]
First column: [10 40 70]
Element at (1,2): 60
Last row: [70 80 90]


##Mathematical operations on a NumPy array

###1. Basic Arithmetic Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Addition: [5 7 9]
print(a - b)  # Subtraction: [-3 -3 -3]
print(a * b)  # Multiplication: [4 10 18]
print(a / b)  # Division: [0.25 0.4 0.5]
print(a % b)  # Modulo: [1 2 3]
print(a ** 2) # Power: [1 4 9]
### print(np.add(a,b)) print(np.subtract(a,b)) print(np.multiply(a,b)) print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[1 4 9]
[5 7 9]


###2. Aggregate Functions

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))      # Sum: 15
print(np.mean(arr))     # Mean: 3.0
print(np.median(arr))   # Median: 3.0
print(np.min(arr))      # Minimum: 1
print(np.max(arr))      # Maximum: 5
print(np.std(arr))      # Standard deviation
print(np.var(arr))      # Variance

###3. Trigonometric Functions

In [ ]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # [0. 1. 0.]
print(np.cos(angles))  # [1. 0. -1.]
print(np.tan(angles))  # [0. 1. 0.]

###4. Exponential and Logarithmic Functions

In [ ]:
values = np.array([1, 2, 3])

print(np.exp(values))  # Exponential: [2.718 7.389 20.08]
print(np.log(values))  # Natural log: [0. 0.693 1.099]
print(np.log10(values)) # Log base 10

###5. Linear Algebra Operations

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print(np.dot(A, B))  # Matrix multiplication
print(np.linalg.det(A))  # Determinant of A
print(np.linalg.inv(A))  # Inverse of A

##Array manipulation

###1. Reshaping
numpy.reshape(a, newshape): Changes the shape of an array.

numpy.ravel(a): Flattens the array into 1D.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.reshape(3, 2))  # Changes shape
print(arr.ravel())        # Flattens to [1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


###2. Transposing
numpy.transpose(a): Swaps rows and columns.

a.T: Shortcut for transposing.

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr.T)  # [[1 3] [2 4]]

###3. Joining & Splitting
numpy.concatenate((a1, a2), axis): Joins arrays.

numpy.split(a, sections): Splits an array.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b)))  # [1 2 3 4 5 6]
print(np.split(a, 3))          # [array([1]), array([2]), array([3])]

###4. Adding & Removing Elements
numpy.append(a, values): Adds elements to an array.

numpy.delete(a, index): Removes elements.

In [ ]:
arr = np.array([1, 2, 3])
print(np.append(arr, 4))   # [1 2 3 4]
print(np.delete(arr, 1))   # [1 3]

###5. Changing Dimensions
numpy.expand_dims(a, axis): Adds a new dimension.

numpy.squeeze(a): Removes single-dimensional axes.

In [ ]:
arr = np.array([1, 2, 3])
print(np.expand_dims(arr, axis=0))  # [[1 2 3]]
squeezed = np.squeeze(arr)
print(squeezed)

[[1 2 3]]
[1 2 3]
